<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Subject;
use Illuminate\Support\Str;

class SubjectSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'emoji' => '🧮',
                'name' => 'Business, Management & Finance',
                'children' => [
                    'Accounting',
                    'Finance',
                    'Business Management',
                    'Human Resource Management',
                    'Marketing',
                    'Digital Marketing',
                    'Business Analytics',
                    'Entrepreneurship',
                    'International Business',
                    'Operations Management',
                    'Supply Chain Management',
                    'Project Management',
                    'Strategic Management',
                    'Leadership Studies',
                    'Corporate Governance',
                    'Business Law',
                    'Risk Management',
                    'Organisational Behaviour',
                    'Innovation Management',
                    'E-commerce',
                    'Business Ethics',
                    'Economics for Business',
                ],
            ],
            [
                'emoji' => '💼',
                'name' => 'Economics & Finance',
                'children' => [
                    'Economics (Micro/Macro)',
                    'International Economics',
                    'Development Economics',
                    'Econometrics',
                    'Financial Economics',
                    'Public Finance',
                    'Banking and Financial Services',
                    'Investment & Portfolio Management',
                    'Behavioural Economics',
                    'Monetary Policy',
                ],
            ],
            [
                'emoji' => '⚖️',
                'name' => 'Law & Criminology',
                'children' => [
                    'Law (LLB & LLM)',
                    'Criminal Law',
                    'Contract Law',
                    'Tort Law',
                    'Constitutional Law',
                    'Family Law',
                    'Employment Law',
                    'Corporate and Commercial Law',
                    'Human Rights Law',
                    'International Law',
                    'Environmental Law',
                    'Immigration Law',
                    'Intellectual Property Law',
                    'Criminology',
                    'Forensic Studies',
                ],
            ],
            [
                'emoji' => '🧠',
                'name' => 'Psychology, Sociology & Social Sciences',
                'children' => [
                    'Psychology',
                    'Counselling Psychology',
                    'Cognitive Psychology',
                    'Clinical Psychology',
                    'Social Psychology',
                    'Educational Psychology',
                    'Sociology',
                    'Social Work',
                    'Criminology & Criminal Justice',
                    'Anthropology',
                    'Gender Studies',
                    'Cultural Studies',
                    'Politics & International Relations',
                    'Public Policy',
                    'Social Policy',
                ],
            ],
            [
                'emoji' => '🧑‍🏫',
                'name' => 'Education & Teaching',
                'children' => [
                    'Education Studies',
                    'Early Childhood Studies',
                    'Primary Education',
                    'Secondary Education',
                    'TESOL (Teaching English to Speakers of Other Languages)',
                    'Special Educational Needs (SEN)',
                    'Curriculum Development',
                    'Educational Leadership',
                    'Higher Education Studies',
                ],
            ],
            [
                'emoji' => '💻',
                'name' => 'Computer Science & IT',
                'children' => [
                    'Computer Science',
                    'Information Technology',
                    'Software Engineering',
                    'Cyber Security',
                    'Data Science',
                    'Artificial Intelligence (AI)',
                    'Machine Learning',
                    'Web Development',
                    'Cloud Computing',
                    'Computer Networks',
                    'Blockchain Technology',
                    'Information Systems Management',
                    'Game Development',
                ],
            ],
            [
                'emoji' => '⚙️',
                'name' => 'Engineering & Technology',
                'children' => [
                    'Civil Engineering',
                    'Mechanical Engineering',
                    'Electrical Engineering',
                    'Electronic Engineering',
                    'Chemical Engineering',
                    'Aerospace Engineering',
                    'Automotive Engineering',
                    'Biomedical Engineering',
                    'Industrial Engineering',
                    'Robotics and Mechatronics',
                    'Structural Engineering',
                    'Renewable Energy Engineering',
                ],
            ],
            [
                'emoji' => '🌿',
                'name' => 'Environmental & Earth Sciences',
                'children' => [
                    'Environmental Science',
                    'Sustainability & Climate Change',
                    'Geography',
                    'Geology',
                    'Oceanography',
                    'Environmental Management',
                    'Conservation Studies',
                    'Ecology',
                ],
            ],
            [
                'emoji' => '🧬',
                'name' => 'Health & Life Sciences',
                'children' => [
                    'Nursing',
                    'Midwifery',
                    'Public Health',
                    'Health and Social Care',
                    'Biomedical Science',
                    'Medicine',
                    'Dentistry',
                    'Pharmacy',
                    'Nutrition and Dietetics',
                    'Physiotherapy',
                    'Occupational Therapy',
                    'Sports Science',
                    'Health Informatics',
                ],
            ],
            [
                'emoji' => '🏛️',
                'name' => 'Arts, Humanities & Culture',
                'children' => [
                    'History',
                    'English Literature',
                    'Linguistics',
                    'Philosophy',
                    'Theology & Religious Studies',
                    'Classics',
                    'Film & Media Studies',
                    'Journalism',
                    'Creative Writing',
                    'Cultural Studies',
                    'Archaeology',
                    'Music',
                    'Performing Arts',
                    'Art History',
                    'Fine Art',
                    'Photography',
                    'Design Studies',
                ],
            ],
            [
                'emoji' => '📢',
                'name' => 'Communication, Media & Marketing',
                'children' => [
                    'Public Relations',
                    'Media & Communication Studies',
                    'Advertising',
                    'Branding',
                    'Journalism',
                    'Film Production',
                    'Digital Media',
                    'Social Media Management',
                ],
            ],
            [
                'emoji' => '🌍',
                'name' => 'Tourism, Hospitality & Events',
                'children' => [
                    'Hospitality Management',
                    'Tourism Management',
                    'Event Management',
                    'Travel & Leisure Studies',
                    'Hotel Operations',
                    'Food and Beverage Management',
                    'Sustainable Tourism',
                    'Destination Marketing',
                ],
            ],
            [
                'emoji' => '🏗️',
                'name' => 'Architecture, Real Estate & Construction',
                'children' => [
                    'Architecture',
                    'Interior Design',
                    'Urban Planning',
                    'Real Estate Management',
                    'Quantity Surveying',
                    'Construction Project Management',
                    'Building Services Engineering',
                ],
            ],
            [
                'emoji' => '📊',
                'name' => 'Mathematics, Statistics & Analytics',
                'children' => [
                    'Mathematics',
                    'Statistics',
                    'Applied Mathematics',
                    'Data Analytics',
                    'Financial Mathematics',
                    'Actuarial Science',
                    'Operations Research',
                ],
            ],
            [
                'emoji' => '🧾',
                'name' => 'Public Administration & Governance',
                'children' => [
                    'Public Administration',
                    'International Development',
                    'Public Policy and Management',
                    'Non-Profit Management',
                    'Governance & Leadership',
                    'Urban Studies',
                ],
            ],
            [
                'emoji' => '🎭',
                'name' => 'Creative Industries & Design',
                'children' => [
                    'Graphic Design',
                    'Fashion Design',
                    'Product Design',
                    'Interior Design',
                    'Animation',
                    'Film Production',
                    'Performing Arts',
                    'Theatre Studies',
                ],
            ],
            [
                'emoji' => '💬',
                'name' => 'Language & Linguistics',
                'children' => [
                    'English Language',
                    'Modern Languages (French, Spanish, German, Italian)',
                    'Translation Studies',
                    'Applied Linguistics',
                    'Interpreting',
                    'Comparative Literature',
                ],
            ],
        ];

        foreach ($categories as $category) {
            $parent = Subject::create([
                'name' => $category['name'],
                'slug' => Str::slug($category['name']),
                'emoji' => $category['emoji'],
            ]);

            foreach ($category['children'] as $child) {
                Subject::create([
                    'name' => $child,
                    'slug' => Str::slug($child),
                    'parent_id' => $parent->id,
                ]);
            }
        }
    }
}
