---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bullwrit/public_html/
    - /bin/rsync -a --delete --exclude '.git' --exclude 'storage/' --exclude '.env' --exclude 'node_modules/' --exclude 'vendor/' ./ $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php /home/bullwrit/wewriteforyou/composer.phar install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan key:generate --force
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
